/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts
 * Generated: 2026-07-15T18:39:47.538Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const cyclonesDashboardTheme: DefinedTheme;
